name: Django CI
run-name: Django CI Fiap
on:
  push:
    branches: [ "develop" ]
    tags: ["*"]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - name: Assegurando copia do repositorio
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  release:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/*')
    runs-on: ubuntu-latest
    steps:
    - name: Assegurando copia do repositorio
      uses: actions/checkout@v4

    - name: Realizando login no dockerhub
      env:
        DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_REPOSITORY }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: 'docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}'

    - name: Gerando imagem ${{ github.ref_name }}
      run:  'docker buildx build -t ${{ DOCKER_HUB_REPOSITORY }}:${{ github.ref_name }} .'

    - name: Realizando push para o dockerhub
      run: 'docker push ${{ DOCKER_HUB_REPOSITORY }}:${{ github.ref_name }}'